# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20151216_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='people_listening',
            field=models.IntegerField(default=None),
        ),
    ]
