# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20151216_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='people_listening',
            field=models.IntegerField(null=True),
        ),
    ]
