# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_user_pic_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
