# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20160104_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
