# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20151216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_message',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CustomUser'),
        ),
    ]
