# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_slug', models.CharField(db_index=True, default='default', max_length=200)),
                ('object_id', models.TextField()),
                ('object_id_int', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('meta_encoded', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'search entries',
            },
        ),
    ]
